apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-app
  template:
    metadata:
      labels:
        app: csv-app
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: csv-app-nginx-conf
            items:
              - key: default.conf
                path: default.conf
      initContainers:
        - name: init-static
          image: csv-app:latest
          command: ["sh","-c","mkdir -p /usr/share/nginx/html/static && cp -r /app/static/* /usr/share/nginx/html/static/"]
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      containers:
        - name: app
          image: csv-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
