name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker secrets
        id: check
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "missing=true" >> $GITHUB_OUTPUT
          else
            echo "missing=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        if: steps.check.outputs.missing == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: steps.check.outputs.missing == 'false'
        uses: docker/build-push-action@v5
        with:
            context: ./app
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/soh-processor:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/soh-processor:${{ github.sha }}

      - name: Skip (no secrets)
        if: steps.check.outputs.missing == 'true'
        run: echo "Docker Hub secrets missing; skipping image push."